name : "running linux command"
on:
  pull_request:  # 

jobs:
  hello:
    runs-on: ubuntu-latest # Runnr/Guthub runner, Its a Github hosted runner

    steps:  # you can execute your own commands
      - name: Print Message
        run: echo "Welcome git push"